### ISSUE TITLE
Arreglar menú de navegación. Cambiar color y corregir Regiter. Y cambiar de color Welcome.

### ISSUE THREAD

**Issue by AnitaMari** [geekhadev/openfeedback#18]
En negro no se ve bien con el fondo tan oscuro que hay, así que voy a poner otro color en consonancia con los que hay (rosa/malva).
Y voy a corregir la palabra Regiter y poner Register.

**Comment by AnitaMari** [comment]
Ya hice la pull request. Si a alguien no le gusta los colores que elegí puede cambiarlos.

**Comment by geekhadev** [comment]
Se cierra con la PR #19
