### ISSUE TITLE
Borrar las cadenas magicas

### ISSUE THREAD

**Issue by Daniel9822** [geekhadev/openfeedback#6]
Propongo eliminar las cadenas mágicas, creando una carpeta de constantes donde se almacenen las cadenas que se utilizarán en la página, de esta manera, tendremos un código más desacoplado y sabremos de antemano dónde se encuentran cuando necesitemos cambiar alguna de ellas.

**Comment by geekhadev** [comment]
Se acepto el PR, podrías verificar si está cubierta este issue y nos confirmas para cerrarlo. Gracias!

**Comment by Daniel9822** [comment]
Sí, está cubierta 🤓

**Comment by geekhadev** [comment]
Resuelto con la PR#7 https://github.com/geekhadev/openfeedback/pull/7
close #6
